// Code generated by codegen/getopenapiof. DO NOT EDIT.

package nano

import (
	"unsafe"

	"github.com/pkg/errors"
)

func (bot *Bot) getOpenAPIofShardWSSGateway(ep string) (*ShardWSSGateway, error) {
	resp := &struct {
		CodeMessageBase
		ShardWSSGateway
	}{}
	err := bot.GetOpenAPI(ep, "", resp)
	if err != nil {
		err = errors.Wrap(err, getCallerFuncName())
	}
	return (*ShardWSSGateway)(unsafe.Add(unsafe.Pointer(resp), unsafe.Sizeof(CodeMessageBase{}))), err
}

func (bot *Bot) getOpenAPIofUser(ep string) (*User, error) {
	resp := &struct {
		CodeMessageBase
		User
	}{}
	err := bot.GetOpenAPI(ep, "", resp)
	if err != nil {
		err = errors.Wrap(err, getCallerFuncName())
	}
	return (*User)(unsafe.Add(unsafe.Pointer(resp), unsafe.Sizeof(CodeMessageBase{}))), err
}

func (bot *Bot) getOpenAPIofGuild(ep string) (*Guild, error) {
	resp := &struct {
		CodeMessageBase
		Guild
	}{}
	err := bot.GetOpenAPI(ep, "", resp)
	if err != nil {
		err = errors.Wrap(err, getCallerFuncName())
	}
	return (*Guild)(unsafe.Add(unsafe.Pointer(resp), unsafe.Sizeof(CodeMessageBase{}))), err
}

func (bot *Bot) getOpenAPIofChannel(ep string) (*Channel, error) {
	resp := &struct {
		CodeMessageBase
		Channel
	}{}
	err := bot.GetOpenAPI(ep, "", resp)
	if err != nil {
		err = errors.Wrap(err, getCallerFuncName())
	}
	return (*Channel)(unsafe.Add(unsafe.Pointer(resp), unsafe.Sizeof(CodeMessageBase{}))), err
}

func (bot *Bot) getOpenAPIofMember(ep string) (*Member, error) {
	resp := &struct {
		CodeMessageBase
		Member
	}{}
	err := bot.GetOpenAPI(ep, "", resp)
	if err != nil {
		err = errors.Wrap(err, getCallerFuncName())
	}
	return (*Member)(unsafe.Add(unsafe.Pointer(resp), unsafe.Sizeof(CodeMessageBase{}))), err
}

func (bot *Bot) getOpenAPIofRoleMembers(ep string) (*RoleMembers, error) {
	resp := &struct {
		CodeMessageBase
		RoleMembers
	}{}
	err := bot.GetOpenAPI(ep, "", resp)
	if err != nil {
		err = errors.Wrap(err, getCallerFuncName())
	}
	return (*RoleMembers)(unsafe.Add(unsafe.Pointer(resp), unsafe.Sizeof(CodeMessageBase{}))), err
}

func (bot *Bot) getOpenAPIofGuildRoleList(ep string) (*GuildRoleList, error) {
	resp := &struct {
		CodeMessageBase
		GuildRoleList
	}{}
	err := bot.GetOpenAPI(ep, "", resp)
	if err != nil {
		err = errors.Wrap(err, getCallerFuncName())
	}
	return (*GuildRoleList)(unsafe.Add(unsafe.Pointer(resp), unsafe.Sizeof(CodeMessageBase{}))), err
}

func (bot *Bot) getOpenAPIofChannelPermissions(ep string) (*ChannelPermissions, error) {
	resp := &struct {
		CodeMessageBase
		ChannelPermissions
	}{}
	err := bot.GetOpenAPI(ep, "", resp)
	if err != nil {
		err = errors.Wrap(err, getCallerFuncName())
	}
	return (*ChannelPermissions)(unsafe.Add(unsafe.Pointer(resp), unsafe.Sizeof(CodeMessageBase{}))), err
}

func (bot *Bot) getOpenAPIofMessage(ep string) (*Message, error) {
	resp := &struct {
		CodeMessageBase
		Message
	}{}
	err := bot.GetOpenAPI(ep, "", resp)
	if err != nil {
		err = errors.Wrap(err, getCallerFuncName())
	}
	return (*Message)(unsafe.Add(unsafe.Pointer(resp), unsafe.Sizeof(CodeMessageBase{}))), err
}
