// Code generated by codegen/putopenapiof. DO NOT EDIT.

package nano

import (
	"io"
	"unsafe"

	"github.com/pkg/errors"
)

func (bot *Bot) putOpenAPIofGuildRoleChannelID(ep string, body io.Reader) (*GuildRoleChannelID, error) {
	resp := &struct {
		CodeMessageBase
		GuildRoleChannelID
	}{}
	err := bot.PutOpenAPI(ep, "", resp, body)
	if err != nil {
		err = errors.Wrap(err, getCallerFuncName())
	}
	return (*GuildRoleChannelID)(unsafe.Add(unsafe.Pointer(resp), unsafe.Sizeof(CodeMessageBase{}))), err
}
