// Code generated by codegen/putopenapiof. DO NOT EDIT.

package nano

import (
	"io"

	"github.com/pkg/errors"
)

func (bot *Bot) putOpenAPIofGuildRoleChannelID(ep string, body io.Reader) (*GuildRoleChannelID, error) {
	resp := &struct {
		CodeMessageBase
		GuildRoleChannelID
	}{}
	err := bot.PutOpenAPI(ep, "", resp, body)
	if err != nil {
		err = errors.Wrap(err, getCallerFuncName())
	}
	return &resp.GuildRoleChannelID, err
}

func (bot *Bot) putOpenAPIofPinsMessage(ep string, body io.Reader) (*PinsMessage, error) {
	resp := &struct {
		CodeMessageBase
		PinsMessage
	}{}
	err := bot.PutOpenAPI(ep, "", resp, body)
	if err != nil {
		err = errors.Wrap(err, getCallerFuncName())
	}
	return &resp.PinsMessage, err
}
