// Code generated by codegen/postopenapiof. DO NOT EDIT.

package nano

import (
	"io"
	"unsafe"

	"github.com/pkg/errors"
)

func (bot *Bot) postOpenAPIofChannel(ep string, body io.Reader) (*Channel, error) {
	resp := &struct {
		CodeMessageBase
		Channel
	}{}
	err := bot.PostOpenAPI(ep, resp, body)
	if err != nil {
		err = errors.Wrap(err, getCallerFuncName())
		return nil, err
	}
	return (*Channel)(unsafe.Add(unsafe.Pointer(resp), unsafe.Sizeof(CodeMessageBase{}))), nil
}

func (bot *Bot) postOpenAPIofGuildRoleCreate(ep string, body io.Reader) (*GuildRoleCreate, error) {
	resp := &struct {
		CodeMessageBase
		GuildRoleCreate
	}{}
	err := bot.PostOpenAPI(ep, resp, body)
	if err != nil {
		err = errors.Wrap(err, getCallerFuncName())
		return nil, err
	}
	return (*GuildRoleCreate)(unsafe.Add(unsafe.Pointer(resp), unsafe.Sizeof(CodeMessageBase{}))), nil
}
